### ISSUE TITLE
Would it be possible to add the industry rating

### ISSUE THREAD

**Issue by superher1** [ldnelson16/On3WebScraper#1]
Jermiah Smith and Dylan Raiola both have 98.76 as the industry ranking in the 2024 class. Would that be possible to add? (i got errors when i tried, but i'm bad at this)

**Comment by ldnelson16** [comment]
I absolutely could, I will be cleaning up the website I have created for it at lukednelson.com/ldnrecruits over the next few days, and will most likely have new features with it, this could be one. The one thing is that I am trying to replace the industry rankings, and so another way which I could avoid ties are to factor in the ordering of the players, for example on 247 or other sites, while many 5 stars are ranked 98, they are in a specific order, whereas on my site, all 98 ratings are valued the same.
